<a href="https://colab.research.google.com/github/SonashreeV/YBI_Internship/blob/main/Women_Cloth_Reviews_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

**Objective:**

The objective of this project is to utilize Multinomial Naive Bayes to predict the sentiment of women's clothing reviews. By analyzing review text data, the project aims to build a model that can categorize reviews accurately, facilitating better understanding of customer opinions and aiding in the improvement of product offerings and marketing strategies.

**Data source:**
https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv




**Import Library**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Import Data**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

**Describe data**

In [3]:
df.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

**Data Visualization**

In [4]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


**Data preprocessing**

In [6]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [7]:
df[df['Review']==""] = np.NaN
df['Review'].fillna("No review is given", inplace=True)
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [8]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**Define Target Variable (y) and Feature Variables (X)**

In [9]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [12]:
x = df['Review']


In [13]:
y = df['Rating']


In [14]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Train Test Split**

In [16]:
from sklearn.model_selection import  train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7,stratify=y,random_state=2529)


In [18]:
x_train.shape, x_test.shape, y_train.shape , y_test.shape

((7045,), (16441,), (7045,), (16441,))

*Getting Tokens from Feature Text*

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)
x_train = cv.fit_transform(x_train)
cv.get_feature_names_out()

array(['00 big', '00 petite', '00 regular', ..., 'zipper works',
       'zipper zip', 'zippers buttons'], dtype=object)

In [20]:
x_train.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
x_test = cv.fit_transform(x_test)
cv.get_feature_names_out()

array(['00 fits', '00 petite', '00p 0p', ..., 'zipper sure',
       'zipper wouldn', 'zippers buttons'], dtype=object)

In [22]:
x_test.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Modeling**

In [23]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

**Model prediction**

In [24]:
y_pred = model.predict(x_test)
y_pred.shape


(16441,)

In [25]:
y_pred

array([1, 1, 4, ..., 2, 5, 3])

In [26]:
model.predict_proba(x_test)


array([[7.34548581e-01, 2.07395900e-01, 5.56068302e-02, 2.39660318e-03,
        5.20864486e-05],
       [9.78996414e-01, 1.23324027e-02, 8.37122599e-03, 8.53226313e-05,
        2.14634878e-04],
       [2.03972443e-02, 1.01153252e-02, 1.22271303e-02, 8.84380323e-01,
        7.28799768e-02],
       ...,
       [1.91499959e-01, 7.11746426e-01, 7.13106646e-02, 2.48899459e-02,
        5.53004124e-04],
       [8.70337166e-02, 7.21556371e-02, 6.22192952e-02, 3.83999758e-01,
        3.94591593e-01],
       [2.39070283e-01, 2.87309835e-01, 4.15209564e-01, 5.82203281e-02,
        1.89990133e-04]])

**Model evaluation**

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[  48   91  106  136  208]
 [ 149  219  212  255  261]
 [ 311  375  386  444  494]
 [ 597  715  707  708  827]
 [1509 1741 1786 1759 2397]]


In [28]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.02      0.08      0.03       589
           2       0.07      0.20      0.10      1096
           3       0.12      0.19      0.15      2010
           4       0.21      0.20      0.21      3554
           5       0.57      0.26      0.36      9192

    accuracy                           0.23     16441
   macro avg       0.20      0.19      0.17     16441
weighted avg       0.39      0.23      0.27     16441



**Explanation:**

This project is focused on building a prediction model. At first, the all required libraries and a test dataset are imported. The dataset was evaluated and pre processed to prepare for it for processing, then a portion of it was kept for testing and the rest was used to train the model. The model was used to get some prediction dataset. Finnaly, prediction accuracy was checked against the test dataset, some adjusment were made and the model was re-trained for better accuracy.